CREATE DATABASE FARMACIA;

CREATE TABLE AVALIACAO (
    ID int NOT NULL,
    NOTA int,
    SUGESTAO varchar(150),
    PRIMARY KEY(ID)
);

CREATE TABLE CLIENTE (
    CPF varchar(11) NOT NULL,
    AVALIACAO int NOT NULL,
    NUMERO varchar(9),
    FOREIGN KEY(AVALIACAO) REFERENCES AVALIACAO(ID),
    PRIMARY KEY(CPF)
);

CREATE TABLE RECEITAMEDICA (
    ID int NOT NULL,
    MEDICO varchar(50),
    CLIENTE varchar(11),
    FOREIGN KEY(CLIENTE) REFERENCES CLIENTE(CPF),
    PRIMARY KEY(ID)
);

CREATE TABLE CAIXA (
    ID int NOT NULL,
    ATENDENTE varchar(50),
    PRIMARY KEY(ID)
);

CREATE TABLE FUNCIONARIO (
    CPF varchar(11) NOT NULL,
    NOME varchar(50),
    CARGAHORARIA int,
    SALARIO float,
    TELEFONE varchar(9),
    PRIMARY KEY(CPF)
);

CREATE TABLE FORNECEDOR (
    ID int NOT NULL,
    FUNCIONARIO varchar(11),
    TELEFONE varchar(9),
    CATALOGO varchar(150),
    FOREIGN KEY(FUNCIONARIO) REFERENCES FUNCIONARIO(CPF),
    PRIMARY KEY(ID)
);

CREATE TABLE MEDICAMENTO (
    ID int NOT NULL,
    FORNECEDOR int NOT NULL,
    TARJA varchar(50),
    DESCRICAO varchar(150),
    CATEGORIA int,
    VALOR float,

    FOREIGN KEY(FORNECEDOR) REFERENCES FORNECEDOR(ID),
    PRIMARY KEY(ID)
);

CREATE TABLE COMPRA (
    ID int NOT NULL,
    RECEITA int,
    CLIENTE varchar(11),
    CAIXA int,
    MEDICAMENTO int,
    FOREIGN KEY(RECEITA) REFERENCES RECEITAMEDICA(ID),
    FOREIGN KEY(CLIENTE) REFERENCES CLIENTE(CPF),
    FOREIGN KEY(CAIXA) REFERENCES CAIXA(ID),
    FOREIGN KEY(MEDICAMENTO) REFERENCES MEDICAMENTO(ID),
    PRIMARY KEY(ID)
);

CREATE TABLE ESTOQUE (
    ID int NOT NULL,
    FUNCIONARIO varchar(11),
    MEDICAMENTO int,
    FORNECEDOR int,
    QTD_ITENS int,
    FOREIGN KEY(FUNCIONARIO) REFERENCES FUNCIONARIO(CPF),
    FOREIGN KEY(MEDICAMENTO) REFERENCES MEDICAMENTO(ID),
    FOREIGN KEY(FORNECEDOR) REFERENCES FORNECEDOR(ID),
    PRIMARY KEY(ID)
);

CREATE TABLE VENDA (
    ID int NOT NULL,
    FUNCIONARIO varchar(11),
    DATA date,
    VALOR float,
    QTD_ITENS int,
    FOREIGN KEY(FUNCIONARIO) REFERENCES FUNCIONARIO(CPF),
    PRIMARY KEY(ID)
);